server:
  port: 8080
  error:
    whitelabel:
      enabled: false
  servlet:
    context-path: /api

spring:
  # TODO : PUSH 하기 전에 다시 한번 확인할 것.
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_DOMAIN}:${DB_PORT}/planit?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    show-sql: true
    hibernate:
      format_sql: true
#      ddl-auto: create
      ddl-auto: none

  #socket test
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: false
  freemarker:
    cache: false

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
      springframework:
        boot:
          autoconfigure: info
